CREATE TABLE MEMBER (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_DATE DATETIME NOT NULL
);